security:
    password_hashers:
        App\Entity\User:
            algorithm: argon2id

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(?:_profiler|_wdt)
            security: false

        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: /login
                username_path: email
                password_path: password
                success_handler: App\Security\LoginSuccessHandler
                failure_handler: App\Security\LoginFailureHandler
            logout:
                path: /logout
            remember_me:
                secret: '%kernel.secret%'
            stateless: false

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/initialize, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
