security:
    password_hashers:
        App\Entity\User:
            #            TODO: описать алгоритм и объяснить его выбор (есть статьи на елайбрари)
            algorithm: argon2id

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(?:_profiler|_wdt)
            security: false

        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: App\Security\LoginSuccessHandler
                failure_handler: App\Security\LoginFailureHandler
            logout:
                path: /logout
#            TODO: описать механизм ремембер ми и объяснить его выбор
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: '/'
                token_provider: { doctrine: true }
                signature_properties: [ 'password' ]
                remember_me_parameter: _remember_me
            stateless: false

    access_control:
        # публичные эндпоинты аутентификации
        - { path: ^/api/login,      roles: PUBLIC_ACCESS }
        - { path: ^/api/register,   roles: PUBLIC_ACCESS }
        - { path: ^/logout,         roles: PUBLIC_ACCESS }
        - { path: ^/register,       roles: PUBLIC_ACCESS }
        - { path: ^/initialize,     roles: PUBLIC_ACCESS }
        # весь REST API защищаем (подставь свой префикс api)
        - { path: ^/api,            roles: IS_AUTHENTICATED_FULLY }
        # всё остальное (SPA-роуты) — публичный доступ, отдаём React
        - { path: ^/,               roles: PUBLIC_ACCESS }
